### ISSUE TITLE
http.createServer is not working

### ISSUE THREAD

**Issue by pirumpi** [tessel/runtime#694]
A simple code for http server is not longer working in the Tessel.

```js
var http = require('http');
var srv = http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('okay');
}).listen(8080);
```

**Comment by patcat** [comment]
My issue was in relation to using @pirumpi's tiny-router to run the server, he appears to have fixed the way his library works with the Tessel's latest version - https://github.com/pirumpi/tiny-router/issues/5. Apparently request.url was returning a Buffer but before was returning an String?

My Tessel server now seems to work with his adjustment to his library, so I'm guessing that http servers are working still with this new version :) Might be worth keeping an eye out for any other libraries that might break with that request.url change though.

**Comment by natevw** [comment]
This may have been recently fixed, perhaps just not released as a firmware update:

**Comment by pirumpi** [comment]
Issue fixed with https://github.com/tessel/runtime/pull/689
